site_name: Skautská dokumentace
theme:
  name: material
  language: cs
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Domů: index.md
  - Schůzky: 
    - schuze/index.md
  - Výpravy:
    - vypravy/index.md
  - Tábor:
    - tabor/index.

site_url: https://vupanska.vercel.app
