site_name: Zápisky z výtvarného umění
theme:
  name: material
  language: cs

nav:
  - Úvod: index.md
  - Dějiny umění: 
    - dejiny/index.md
  - Techniky:
    - techniky/index.md
  - Umělci:
    - umelci/index.md

site_url: https://vupanska.vercel.app
