site_name: Zápisky z výtvarného umění
theme:
  name: material
  language: cs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Přepnout na tmavý režim
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Přepnout na světlý režim
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.expand
    - toc.integrate
    - header.autohide
    - content.image.lazy  # Přidat podporu pro lazy loading obrázků
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant
  custom_dir: overrides  # Relativní cesta ke složce overrides

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list  # Povolit atributy pro obrázky
  - md_in_html # Povolit markdown v HTML
  - tables
  - footnotes
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexuspo/vupanska
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - Domů: index.md
  - Dějiny umění: 
    - dejiny/index.md
    - dejiny/praveke-umeni.md
    - dejiny/mezopotamie.md
    - dejiny/judaismus.md
    - dejiny/babylon.md
    - dejiny/egypt.md
    - dejiny/rim.md
    - dejiny/krestanska-antika.md
    - dejiny/byzanc.md
    - dejiny/romanske-umeni.md
    - dejiny/gotika.md
    - dejiny/renesance.md
    - dejiny/claude-monet.md
    - dejiny/baroko.md
    - dejiny/rokoko.md
    - dejiny/klasicismus.md
  - Poznávačky:
    - poznavacky/index.md
    - poznavacky/byzanc.md
  - Užitečné materiály:
    - materialy/index.md
  - Umělci:
    - umelci/index.md

site_url: https://vupanska.vercel.app

# Důležité nastavení pro správnou funkci navigace
use_directory_urls: false
strict: true

site_dir: site
docs_dir: docs

# Důležité nastavení pro zpracování obrázků
docs_dir: docs
site_dir: site
use_directory_urls: false

# Přidat pouze základní pluginy
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      draggable: true
