site_name: Zápisky z výtvarného umění
site_description: Kompletní zápisky z výtvarného umění - dějiny, směry, umělci, poznávačky a studijní materiály
site_author: Alexandr Pomykacz
site_url: https://vupanska.vercel.app

theme:
  name: material
  language: cs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Přepnout na tmavý režim
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Přepnout na světlý režim
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.expand
    - toc.integrate
    - header.autohide
    - content.image.lazy  # Přidat podporu pro lazy loading obrázků
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/book-open-page-variant
  custom_dir: overrides  # Relativní cesta ke složce overrides

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list  # Povolit atributy pro obrázky
  - md_in_html # Povolit markdown v HTML
  - tables
  - footnotes
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexuspo/vupanska
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  # Enhanced metadata
  meta:
    - name: keywords
      content: výtvarné umění, dějiny umění, kubismus, abstraktní umění, poznávačky, umělecké směry
  # Open Graph
  open_graph:
    type: website
    site_name: Zápisky z výtvarného umění
    image: assets/images/og-image.png  # You should create this image
  # Twitter
  twitter:
    creator: "@vupanska"
    card: summary_large_image

  generator: false

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Domů: index.md
  - Dějiny:
    - dejiny/index.md
    - dejiny/praveke-umeni.md
    - dejiny/mezopotamie.md
    - dejiny/judaismus.md
    - dejiny/babylon.md
    - dejiny/egypt.md
    - dejiny/rim.md
    - dejiny/krestanska-antika.md
    - dejiny/byzanc.md
    - dejiny/romanske-umeni.md
    - dejiny/gotika.md
    - dejiny/renesance.md
    - dejiny/claude-monet.md
    - dejiny/baroko.md
    - dejiny/rokoko.md
    - dejiny/klasicismus.md
    - dejiny/romantismus.md
    - dejiny/abstraktni-umeni.md
  - Shrnutí:
    - shrnuti/index.md
    - shrnuti/vyvoj-umeni.md
    - shrnuti/novoveke-umeni.md
    - shrnuti/moderni-umeni.md
    - shrnuti/abstraktni-umeni.md
    - shrnuti/kubismus.md
    - shrnuti/cesky-kubismus.md
    - shrnuti/futurismus-konstruktivismus.md
  - Poznávačky:
    - poznavacky/index.md
    - poznavacky/byzanc.md
  - Kartičky:
    - karticky/index.md
  - Užitečné materiály:
    - materialy/index.md

site_url: https://vupanska.vercel.app

# Důležité nastavení pro správnou funkci navigace
use_directory_urls: false
strict: true

site_dir: site
docs_dir: docs

# Důležité nastavení pro zpracování obrázků
docs_dir: docs
site_dir: site
use_directory_urls: false

# Přidat pouze základní pluginy
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      draggable: true

markdown_extensions:
  - attr_list
  - md_in_html
