site_name: Zápisky z výtvarného umění
theme:
  name: material
  language: cs

nav:
  - Úvod: index.md
  - Dějiny umění: 
    - dejiny/index.md
    - dejiny/praveke-umeni.md
    - dejiny/mezopotamie.md
    - dejiny/judaismus.md
    - dejiny/babylon.md
    - dejiny/egypt.md
  - Techniky:
    - techniky/index.md
  - Umělci:
    - umelci/index.md

site_url: https://vupanska.vercel.app
site_dir: site
docs_dir: docs
use_directory_urls: false
strict: true
